export const courses = {
    timezone: "PST",
    dateFormat: "YYYY-MM-DD",
    classes: [
        {
            class: "Introduction to JavaScript",
            classType: "Introduction",
            classId: "04075A",
            subject: "js",
            startDate: "2024-04-07",
            startTime: "1500",
            sessions: 8,
            studentCount: 6,
            lessons: [
                {
                    id: 1,
                    lesson: [
                        "welcome-to-introduction-to-JavaScript",
                        "introduction-to-JavaScript",
                    ],
                },
                {
                    id: 2,
                    lesson: [
                        "control-flow-functions-and-arrow-functions-in-JavaScript",
                        "arrow-functions-in-JavaScript",
                        "JavaScript-functions-exercise",
                    ],
                },
            ],
        },
        {
            class: "Introduction to JavaScript",
            classType: "Introduction",
            classId: "031612A",
            subject: "js",
            startDate: "2024-03-16",
            startTime: "1000",
            sessions: 8,
            studentCount: 4,
            lessons: [
                { id: 1, lesson: ["introduction-to-JavaScript"] },
                {
                    id: 2,
                    lesson: [
                        "control-flow-functions-and-arrow-functions-in-JavaScript",
                    ],
                },
                { id: 3, lesson: ["data-structures-in-JavaScript"] },
                { id: 4, lesson: ["document-object-model-manipulation"] },
                { id: 5, lesson: ["introduction-to-asynchronous-JavaScript"] },
            ],
        },
        {
            class: "Introduction to Python for Adults",
            classType: "Introduction",
            classId: "04106A",
            subject: "py",
            startDate: "2024-04-10",
            startTime: "1630",
            sessions: 8,
            studentCount: 15,
            lessons: [{ id: 1, lesson: ["introduction-to-python"] }],
        },
        {
            class: "Using Chat-GPT for Students & Young Professionals",
            classType: "Introduction",
            classId: "04028A",
            subject: "it",
            startDate: "2024-04-09",
            startTime: "1800",
            sessions: 3,
            studentCount: 7,
            lessons: [{ id: 1, lesson: ["introduction-to-AI-and-Chat-GPT"] }],
        },
        {
            class: "Intermediate Python for Adults",
            classType: "Intermediate",
            classId: "03258A",
            subject: "py",
            startDate: "2024-03-25",
            startTime: "1800",
            sessions: 8,
            studentCount: 5,
            lessons: [
                { id: 1, lesson: ["advanced-data-structures"] },
                { id: 2, lesson: ["file-handling-and-IO-operations"] },
                { id: 3, lesson: ["function-programming-in-python"] },
            ],
        },
        {
            class: "Javascript Coding Academy",
            classType: "Academy",
            classId: "033020H",
            subject: "js",
            startDate: "2024-03-30",
            startTime: "830",
            sessions: 4,
            studentCount: 7,
            lessons: [
                { id: 1, lesson: ["introduction-to-JavaScript"] },
                {
                    id: 2,
                    lesson: [
                        "control-flow-functions-and-arrow-functions-in-JavaScript",
                    ],
                },
                { id: 3, lesson: ["data-structures-in-JavaScript"] },
                { id: 4, lesson: ["document-object-model-manipulation"] },
            ],
        },
        {
            class: "Javascript Coding Academy",
            classType: "Academy",
            classId: "03056H",
            subject: "js",
            startDate: "2024-03-19",
            startTime: "1600",
            sessions: 4,
            studentCount: 5,
            lessons: [
                { id: 1, lesson: ["introduction-to-JavaScript"] },
                {
                    id: 2,
                    lesson: [
                        "control-flow-functions-and-arrow-functions-in-JavaScript",
                    ],
                },
                { id: 3, lesson: ["data-structures-in-JavaScript"] },
                { id: 4, lesson: ["document-object-model-manipulation"] },
            ],
        },
    ],
};
